import type { SubjectCurriculum } from "./types";

export const history: SubjectCurriculum = {
  slug: "history",
  lessons: [
    // ===================== WORLD WAR I (6) =====================
    {
      topic: "World War I",
      title: "The Causes of WWI (MAIN)",
      difficulty: "intermediate",
      minutes: 14,
      points: 90,
      summary: "The main long-term causes of WWI are remembered as MAIN: Militarism, Alliances, Imperialism, and Nationalism.",
      blocks: [
        { type: "heading", text: "Why Did the World Go to War?" },
        {
          type: "text",
          text: "World War I did not start from a single cause. Historians use the word MAIN to remember four long-term causes: Militarism (countries built up huge armies and rival navies), Alliances (countries promised to defend each other, so a small fight could pull everyone in), Imperialism (powers competed for colonies and trade), and Nationalism (fierce pride in one's nation, especially in the Balkans).\n\nTogether these created a tense, armed Europe waiting for a spark. When it came, the alliances dragged country after country into war.",
        },
        {
          type: "example",
          text: "Militarism example: Britain and Germany raced to build the most powerful warships (dreadnoughts). Alliances example: the Triple Entente (Britain, France, Russia) faced the Triple Alliance (Germany, Austria-Hungary, Italy).",
        },
        {
          type: "keyPoints",
          items: [
            "M — Militarism: arms race.",
            "A — Alliances: mutual defence pacts.",
            "I — Imperialism: competition for empire.",
            "N — Nationalism: fierce national pride.",
          ],
        },
        {
          type: "interactive",
          variant: "reveal",
          data: [
            { key: "question", value: "What does the 'A' in MAIN stand for?" },
            { key: "option_0", value: "Alliances" },
            { key: "option_1", value: "Army" },
            { key: "option_2", value: "America" },
            { key: "option_3", value: "Aircraft" },
            { key: "answer", value: "Alliances" },
            { key: "explanation", value: "Countries promised to defend each other." },
          ],
        },
      ],
      questions: [
        { q: "What does MAIN stand for in WWI causes?", options: ["Militarism, Alliances, Imperialism, Nationalism", "Money, Army, Industry, Navy", "Monarchs, Arms, Islands, Nations", "Militarism, Army, Industry, Navy"], answer: "Militarism, Alliances, Imperialism, Nationalism", explain: "The four long-term causes." },
        { q: "Militarism refers to…", options: ["building up armed forces", "farming", "trade deals", "art"], answer: "building up armed forces", explain: "Arms race." },
        { q: "Alliances meant a small conflict could…", options: ["pull many countries into war", "end quickly", "be ignored", "lower taxes"], answer: "pull many countries into war", explain: "Defence pacts chained nations in." },
        { q: "Imperialism is competition for…", options: ["colonies and trade", "sports", "music", "science"], answer: "colonies and trade", explain: "Empire-building." },
        { q: "Nationalism is fierce…", options: ["pride in one's nation", "trade", "farming", "industry only"], answer: "pride in one's nation", explain: "Especially in the Balkans." },
      ],
    },
    {
      topic: "World War I",
      title: "The Spark: Sarajevo 1914",
      difficulty: "intermediate",
      minutes: 12,
      points: 80,
      summary: "On 28 June 1914, Archduke Franz Ferdinand was assassinated in Sarajevo — the spark that ignited WWI.",
      blocks: [
        { type: "heading", text: "A Single Shot" },
        {
          type: "text",
          text: "The spark came on 28 June 1914 in Sarajevo, Bosnia. Archduke Franz Ferdinand, heir to the Austro-Hungarian throne, was assassinated by Gavrilo Princip, a young nationalist who wanted independence for Slavic peoples.\n\nAustria-Hungary blamed Serbia and issued harsh demands. Within weeks, the alliance system pulled in Russia, Germany, France and Britain. By early August 1914, Europe was at war. One assassination lit the MAIN powder keg.",
        },
        {
          type: "example",
          text: "Chain reaction: assassination → Austria-Hungary declares war on Serbia → Russia mobilises to protect Serbia → Germany backs Austria-Hungary → France and Britain join → world war.",
        },
        {
          type: "keyPoints",
          items: [
            "28 June 1914: Franz Ferdinand assassinated.",
            "Killer: Gavrilo Princip, a nationalist.",
            "Location: Sarajevo, Bosnia.",
            "It triggered the alliance chain reaction.",
          ],
        },
        {
          type: "interactive",
          variant: "reveal",
          data: [
            { key: "question", value: "Who was assassinated in Sarajevo in 1914?" },
            { key: "option_0", value: "Archduke Franz Ferdinand" },
            { key: "option_1", value: "Kaiser Wilhelm" },
            { key: "option_2", value: "Abraham Lincoln" },
            { key: "option_3", value: "Winston Churchill" },
            { key: "answer", value: "Archduke Franz Ferdinand" },
            { key: "explanation", value: "Heir to the Austro-Hungarian throne." },
          ],
        },
      ],
      questions: [
        { q: "When was Franz Ferdinand assassinated?", options: ["1914", "1918", "1939", "1900"], answer: "1914", explain: "28 June 1914." },
        { q: "Where did the assassination happen?", options: ["Sarajevo", "Berlin", "London", "Paris"], answer: "Sarajevo", explain: "In Bosnia." },
        { q: "Who killed the Archduke?", options: ["Gavrilo Princip", "Kaiser Wilhelm", "Napoleon", "Otto von Bismarck"], answer: "Gavrilo Princip", explain: "A young nationalist." },
        { q: "Austria-Hungary then blamed which country?", options: ["Serbia", "France", "Britain", "Russia"], answer: "Serbia", explain: "Leading to war." },
        { q: "The assassination was the…", options: ["spark that triggered the alliance chain", "end of the war", "cause of WWII", "signing of peace"], answer: "spark that triggered the alliance chain", explain: "MAIN causes had set the stage." },
      ],
    },
    {
      topic: "World War I",
      title: "The Outbreak & Two Sides",
      difficulty: "intermediate",
      minutes: 12,
      points: 80,
      summary: "By August 1914 Europe split into two alliances: the Allies (Entente) and the Central Powers, fighting across multiple fronts.",
      blocks: [
        { type: "heading", text: "Two Sides Form" },
        {
          type: "text",
          text: "Within weeks of Sarajevo, Europe's alliances snapped into two armed camps. The Central Powers were led by Germany and Austria-Hungary (later joined by the Ottoman Empire and Bulgaria). The Allies (or Entente) were led by France, Russia and Britain, later joined by many nations including the United States in 1917.\n\nFighting spread across several fronts. The Western Front cut through France and Belgium. The Eastern Front stretched across Russia and Eastern Europe. There were also fronts in Italy, the Middle East and at sea.",
        },
        {
          type: "example",
          text: "Central Powers: Germany, Austria-Hungary, Ottoman Empire. Allies: Britain, France, Russia (until 1917), Italy (from 1915), USA (from 1917).",
        },
        {
          type: "keyPoints",
          items: [
            "Central Powers: Germany + Austria-Hungary.",
            "Allies (Entente): Britain, France, Russia.",
            "USA joined the Allies in 1917.",
            "Fought on Western, Eastern and other fronts.",
          ],
        },
        {
          type: "interactive",
          variant: "reveal",
          data: [
            { key: "question", value: "Which side did Germany lead in WWI?" },
            { key: "option_0", value: "The Central Powers" },
            { key: "option_1", value: "The Allies (Entente)" },
            { key: "option_2", value: "The Neutral League" },
            { key: "option_3", value: "The Commonwealth" },
            { key: "answer", value: "The Central Powers" },
            { key: "explanation", value: "Germany and Austria-Hungary." },
          ],
        },
      ],
      questions: [
        { q: "Germany and Austria-Hungary were the…", options: ["Central Powers", "Allies", "Neutral", "Commonwealth"], answer: "Central Powers", explain: "The other side." },
        { q: "Britain, France and Russia were the…", options: ["Allies (Entente)", "Central Powers", "Neutral", "Axis"], answer: "Allies (Entente)", explain: "Opposed the Central Powers." },
        { q: "When did the USA join WWI?", options: ["1917", "1914", "1918", "1939"], answer: "1917", explain: "On the Allied side." },
        { q: "The main fighting line in France/Belgium was the…", options: ["Western Front", "Eastern Front", "Home Front", "Maginot Line"], answer: "Western Front", explain: "Trench warfare there." },
        { q: "Which later joined the Central Powers?", options: ["Ottoman Empire", "USA", "Britain", "France"], answer: "Ottoman Empire", explain: "Modern-day Turkey region." },
      ],
    },
    {
      topic: "World War I",
      title: "Trench Warfare",
      difficulty: "intermediate",
      minutes: 14,
      points: 90,
      summary: "On the Western Front, soldiers lived in long muddy trenches facing each other for years in a brutal stalemate.",
      blocks: [
        { type: "heading", text: "Life in the Mud" },
        {
          type: "text",
          text: "On the Western Front, both sides dug long networks of trenches facing each other, sometimes only metres apart. Between them lay 'No Man's Land' — a deadly strip of barbed wire and shell holes. Soldiers endured mud, rats, cold, disease and the constant threat of artillery and gas.\n\nAttacks called 'going over the top' sent men across No Man's Land, but machine guns usually cut them down. For years the front barely moved — a grim stalemate that cost millions of lives for tiny gains.",
        },
        {
          type: "example",
          text: "A typical trench had a fire step for shooting, dugouts for shelter, and sandbag walls. 'Trench foot' (rot from wet feet) and 'shell shock' (trauma) were common.",
        },
        {
          type: "keyPoints",
          items: [
            "Trenches faced each other across No Man's Land.",
            "Machine guns made attacks deadly.",
            "Life was harsh: mud, rats, disease, gas.",
            "Years of stalemate, tiny gains.",
          ],
        },
        {
          type: "interactive",
          variant: "reveal",
          data: [
            { key: "question", value: "The deadly strip between opposing trenches was called…" },
            { key: "option_0", value: "No Man's Land" },
            { key: "option_1", value: "The Western Front" },
            { key: "option_2", value: "The Somme" },
            { key: "option_3", value: "The Maginot Line" },
            { key: "answer", value: "No Man's Land" },
            { key: "explanation", value: "Barbed wire and shell holes between trenches." },
          ],
        },
      ],
      questions: [
        { q: "Trenches were separated by…", options: ["No Man's Land", "a river", "a wall", "a forest"], answer: "No Man's Land", explain: "Deadly strip." },
        { q: "Which weapon made infantry charges deadly?", options: ["Machine guns", "Bows", "Swords", "Spears"], answer: "Machine guns", explain: "Cut down advancing soldiers." },
        { q: "Common trench hardships included…", options: ["mud, rats, disease, gas", "luxury food", "warm baths", "quiet nights"], answer: "mud, rats, disease, gas", explain: "Brutal conditions." },
        { q: "'Going over the top' meant…", options: ["climbing out to attack across No Man's Land", "going home", "digging deeper", "ceasefire"], answer: "climbing out to attack across No Man's Land", explain: "Usually disastrous." },
        { q: "The Western Front was mostly a…", options: ["stalemate", "fast mobile war", "naval battle", "air war"], answer: "stalemate", explain: "Little movement for years." },
      ],
    },
    {
      topic: "World War I",
      title: "Key Battles: Somme & Verdun",
      difficulty: "intermediate",
      minutes: 14,
      points: 90,
      summary: "Verdun (1916) and the Somme (1916) were huge, bloody battles that symbolised the war's terrible cost.",
      blocks: [
        { type: "heading", text: "Battles of Attrition" },
        {
          type: "text",
          text: "Two 1916 battles came to symbolise WWI's horror. At Verdun, Germany attacked France for almost the whole year; France held but roughly 700,000 men on both sides fell. 'They shall not pass' became the French cry.\n\nTo relieve Verdun, Britain launched the Somme on 1 July 1916. The first day was the bloodiest in British army history — about 57,000 casualties in a single day. The battle lasted months and gained only a few kilometres.",
        },
        {
          type: "example",
          text: "1 July 1916, first day of the Somme: ~57,000 British casualties in one day. The battle dragged on until November, with over a million casualties on all sides combined.",
        },
        {
          type: "keyPoints",
          items: [
            "Verdun 1916: Germany vs France, huge losses.",
            "'They shall not pass' — French defence.",
            "Somme 1916: Britain relieves Verdun.",
            "1 July 1916: bloodiest day in British military history.",
          ],
        },
        {
          type: "interactive",
          variant: "reveal",
          data: [
            { key: "question", value: "Why did Britain launch the Battle of the Somme in 1916?" },
            { key: "option_0", value: "To relieve pressure on France at Verdun" },
            { key: "option_1", value: "To sign a peace treaty" },
            { key: "option_2", value: "To capture Berlin" },
            { key: "option_3", value: "To test new tanks only" },
            { key: "answer", value: "To relieve pressure on France at Verdun" },
            { key: "explanation", value: "Draw German forces away from Verdun." },
          ],
        },
      ],
      questions: [
        { q: "Verdun was mainly fought between…", options: ["Germany and France", "Britain and Germany", "USA and Germany", "Russia and Germany"], answer: "Germany and France", explain: "Almost all of 1916." },
        { q: "The first day of the Somme is famous for…", options: ["huge British casualties (~57,000)", "a quick victory", "no fighting", "the armistice"], answer: "huge British casualties (~57,000)", explain: "Bloodiest day in British army history." },
        { q: "Verdun and the Somme were both in…", options: ["1916", "1914", "1918", "1939"], answer: "1916", explain: "Middle of the war." },
        { q: "'They shall not pass' was the cry at…", options: ["Verdun", "the Somme", "D-Day", "Waterloo"], answer: "Verdun", explain: "French defence slogan." },
        { q: "These battles are remembered as…", options: ["symbols of the war's terrible cost", "quick wins", "naval battles", "peace talks"], answer: "symbols of the war's terrible cost", explain: "Enormous casualties, tiny gains." },
      ],
    },
    {
      topic: "World War I",
      title: "End of the War & Treaty of Versailles",
      difficulty: "intermediate",
      minutes: 14,
      points: 90,
      summary: "WWI ended on 11 November 1918; the Treaty of Versailles (1919) punished Germany and helped set up WWII.",
      blocks: [
        { type: "heading", text: "Armistice and Aftermath" },
        {
          type: "text",
          text: "In 1918, the USA's arrival, blockade and revolution weakened the Central Powers. On 11 November 1918 (the 11th hour of the 11th day), Germany signed an armistice — the fighting stopped. About 17 million people had died.\n\nThe 1919 Treaty of Versailles blamed Germany for the war, forced it to pay huge reparations, cut its army and took land away. Many Germans felt humiliated. Historians believe this harsh peace helped create the anger that led to World War II.",
        },
        {
          type: "example",
          text: "11 November 1918, 11am: the guns fell silent. We now mark this as Armistice Day / Remembrance Day, with two minutes' silence.",
        },
        {
          type: "keyPoints",
          items: [
            "Armistice: 11 November 1918, 11am.",
            "~17 million dead worldwide.",
            "Treaty of Versailles (1919) punished Germany.",
            "Harsh terms helped cause WWII.",
          ],
        },
        {
          type: "interactive",
          variant: "timeline",
          data: [
            { key: "1914", value: "War begins after Sarajevo." },
            { key: "1916", value: "Battles of Verdun and the Somme." },
            { key: "1917", value: "USA joins the Allies." },
            { key: "1918", value: "Armistice — fighting stops 11 November." },
            { key: "1919", value: "Treaty of Versailles signed." },
          ],
        },
      ],
      questions: [
        { q: "WWI fighting stopped on…", options: ["11 November 1918", "11 November 1914", "11 September 1918", "1 January 1919"], answer: "11 November 1918", explain: "Armistice Day." },
        { q: "The 1919 peace treaty was signed at…", options: ["Versailles", "Yalta", "Vienna", "Paris only"], answer: "Versailles", explain: "Treaty of Versailles." },
        { q: "The treaty blamed which country for the war?", options: ["Germany", "Britain", "France", "USA"], answer: "Germany", explain: "War guilt clause." },
        { q: "Roughly how many people died in WWI?", options: ["~17 million", "~1 million", "~100 million", "~500,000"], answer: "~17 million", explain: "Military + civilian deaths." },
        { q: "The harsh Treaty of Versailles helped cause…", options: ["World War II", "the Moon landing", "the Renaissance", "the Industrial Revolution"], answer: "World War II", explain: "Resentment in Germany." },
      ],
    },

    // ===================== WORLD WAR II (6) =====================
    {
      topic: "World War II",
      title: "Causes of WWII",
      difficulty: "intermediate",
      minutes: 14,
      points: 90,
      summary: "WWII's causes include the harsh Treaty of Versailles, the Great Depression, and the rise of dictators like Hitler and Mussolini.",
      blocks: [
        { type: "heading", text: "How the Next War Began" },
        {
          type: "text",
          text: "World War II grew from unfinished business and new misery. The Treaty of Versailles left many Germans bitter and poor. The Great Depression (a worldwide economic crash from 1929) made people desperate and willing to listen to strong leaders who promised order and glory.\n\nDictators rose: Adolf Hitler in Germany (Nazism), Benito Mussolini in Italy (Fascism), and militarist leaders in Japan. Hitler broke treaties, rebuilt the army, and seized land while Britain and France tried to avoid another war (appeasement).",
        },
        {
          type: "example",
          text: "Appeasement: at the 1938 Munich Agreement, Britain and France let Hitler take part of Czechoslovakia in exchange for a promise of peace — which he broke within months.",
        },
        {
          type: "keyPoints",
          items: [
            "Versailles' harsh terms angered Germany.",
            "Great Depression (1929) spread desperation.",
            "Dictators: Hitler, Mussolini, Japanese militarists.",
            "Appeasement failed to stop Hitler.",
          ],
        },
        {
          type: "interactive",
          variant: "reveal",
          data: [
            { key: "question", value: "Which economic disaster helped dictators rise?" },
            { key: "option_0", value: "The Great Depression (from 1929)" },
            { key: "option_1", value: "The Dot-Com crash" },
            { key: "option_2", value: "The 2008 crisis" },
            { key: "option_3", value: "The oil crisis" },
            { key: "answer", value: "The Great Depression (from 1929)" },
            { key: "explanation", value: "Mass unemployment fuelled extremism." },
          ],
        },
      ],
      questions: [
        { q: "Who led Nazi Germany?", options: ["Adolf Hitler", "Benito Mussolini", "Joseph Stalin", "Winston Churchill"], answer: "Adolf Hitler", explain: "From 1933." },
        { q: "Appeasement means…", options: ["giving in to avoid war", "attacking first", "ignoring everyone", "making alliances"], answer: "giving in to avoid war", explain: "It failed with Hitler." },
        { q: "The Great Depression began in…", options: ["1929", "1914", "1939", "1945"], answer: "1929", explain: "Worldwide economic crash." },
        { q: "Mussolini led which ideology in Italy?", options: ["Fascism", "Democracy", "Communism", "Monarchy only"], answer: "Fascism", explain: "Authoritarian nationalism." },
        { q: "Which treaty's harshness helped cause WWII?", options: ["Treaty of Versailles", "Treaty of Rome", "NATO treaty", "Geneva Convention"], answer: "Treaty of Versailles", explain: "Resentment in Germany." },
      ],
    },
    {
      topic: "World War II",
      title: "The War Begins (1939–40)",
      difficulty: "intermediate",
      minutes: 14,
      points: 90,
      summary: "Germany invaded Poland on 1 September 1939; Britain and France declared war, beginning WWII in Europe.",
      blocks: [
        { type: "heading", text: "Poland Falls" },
        {
          type: "text",
          text: "On 1 September 1939, Germany invaded Poland using 'Blitzkrieg' — fast, coordinated attacks by tanks and aircraft. Britain and France had promised to defend Poland and declared war on 3 September 1939. World War II in Europe had begun.\n\nGermany and the Soviet Union secretly agreed to split Poland. By mid-1940, Germany had overrun much of Western Europe, including France, using devastating speed. Britain stood alone against Hitler through the desperate summer of 1940.",
        },
        {
          type: "example",
          text: "Blitzkrieg ('lightning war'): Stuka dive-bombers shattered defences, tanks punched through, and infantry followed fast — overwhelming countries in days or weeks.",
        },
        {
          type: "keyPoints",
          items: [
            "1 Sept 1939: Germany invaded Poland.",
            "3 Sept 1939: Britain & France declared war.",
            "Blitzkrieg: fast tank + air attacks.",
            "1940: Germany overran much of Western Europe.",
          ],
        },
        {
          type: "interactive",
          variant: "reveal",
          data: [
            { key: "question", value: "WWII in Europe began when Germany invaded…" },
            { key: "option_0", value: "Poland (1939)" },
            { key: "option_1", value: "France (1940)" },
            { key: "option_2", value: "Britain (1940)" },
            { key: "option_3", value: "Russia (1941)" },
            { key: "answer", value: "Poland (1939)" },
            { key: "explanation", value: "1 September 1939." },
          ],
        },
      ],
      questions: [
        { q: "When did Germany invade Poland?", options: ["1 September 1939", "3 September 1939", "1914", "1941"], answer: "1 September 1939", explain: "Started WWII in Europe." },
        { q: "Blitzkrieg means…", options: ["lightning war", "trench war", "naval war", "cold war"], answer: "lightning war", explain: "Fast tank + air attacks." },
        { q: "Which country declared war on 3 September 1939?", options: ["Britain and France", "USA and Russia", "Italy and Japan", "Spain and Portugal"], answer: "Britain and France", explain: "To defend Poland." },
        { q: "By mid-1940 Germany had overrun much of…", options: ["Western Europe (incl. France)", "North America", "Australia", "South America"], answer: "Western Europe (incl. France)", explain: "Swift conquests." },
        { q: "In summer 1940, which country stood largely alone?", options: ["Britain", "France", "Poland", "Spain"], answer: "Britain", explain: "After France fell." },
      ],
    },
    {
      topic: "World War II",
      title: "The Home Front",
      difficulty: "intermediate",
      minutes: 12,
      points: 80,
      summary: "Civilians faced bombing, rationing, blackouts and new roles as women kept nations running and fighting.",
      blocks: [
        { type: "heading", text: "War at Home" },
        {
          type: "text",
          text: "WWII was a 'total war' — whole societies, not just soldiers, were involved. Cities were bombed from the air; the Blitz on London and other British cities killed tens of thousands but did not break morale. Food, clothes and fuel were rationed so troops could be supplied.\n\nMillions of women took on factory, farm and services jobs once done by men, transforming women's roles. People grew 'victory gardens', salvaged scrap metal, and endured blackouts to hinder air raids. Children were evacuated from cities to the countryside for safety.",
        },
        {
          type: "example",
          text: "The Blitz (1940–41): German bombers pounded London for 76 nights in a row. Families sheltered in tube stations. Morning after morning, people dug out and carried on.",
        },
        {
          type: "keyPoints",
          items: [
            "Total war involved whole societies.",
            "Cities were bombed (e.g. the Blitz).",
            "Rationing limited food, clothes, fuel.",
            "Women took on vital new roles.",
          ],
        },
        {
          type: "interactive",
          variant: "reveal",
          data: [
            { key: "question", value: "Rationing in wartime meant…" },
            { key: "option_0", value: "limiting food/goods so troops could be supplied" },
            { key: "option_1", value: "eating as much as you like" },
            { key: "option_2", value: "only the rich got food" },
            { key: "option_3", value: "importing more food than ever" },
            { key: "answer", value: "limiting food/goods so troops could be supplied" },
            { key: "explanation", value: "Fair shares for all." },
          ],
        },
      ],
      questions: [
        { q: "The Blitz was the bombing of…", options: ["British cities", "Berlin only", "Tokyo", "New York"], answer: "British cities", explain: "Especially London." },
        { q: "WWII is called a 'total war' because…", options: ["whole societies were involved", "only soldiers fought", "it lasted a day", "no one was hurt"], answer: "whole societies were involved", explain: "Civilians + armies." },
        { q: "Many women during WWII…", options: ["took factory/farm/service jobs", "stayed home only", "left the country", "stopped working"], answer: "took factory/farm/service jobs", explain: "Vital to the war effort." },
        { q: "Children in cities were often…", options: ["evacuated to the countryside", "sent to factories", "kept in bomb shelters forever", "ignored"], answer: "evacuated to the countryside", explain: "For safety." },
        { q: "Blackouts aimed to…", options: ["hinder enemy air raids at night", "save money", "make people sleep", "block the sun"], answer: "hinder enemy air raids at night", explain: "Harder to see targets." },
      ],
    },
    {
      topic: "World War II",
      title: "Key Turning Points",
      difficulty: "intermediate",
      minutes: 14,
      points: 90,
      summary: "Three turning points in 1942–43 — Stalingrad, Midway, and El Alamein — shifted the war against the Axis.",
      blocks: [
        { type: "heading", text: "The Tide Turns" },
        {
          type: "text",
          text: "By late 1942 the Axis advance was halted at three crucial battles. At Stalingrad (Soviet Union), a savage months-long battle destroyed a whole German army — the Eastern Front turned against Germany. At Midway (Pacific), the USA sank four Japanese aircraft carriers, swinging the Pacific war.\n\nAt El Alamein (North Africa), Britain's victory ended the Axis threat to the Suez Canal and oil. After these, the Allies went on the offensive on every front.",
        },
        {
          type: "example",
          text: "Stalingrad: street-by-street fighting in bitter cold; the German 6th Army was surrounded and surrendered in early 1943 — a disaster Germany could not replace.",
        },
        {
          type: "keyPoints",
          items: [
            "Stalingrad (1942–43): stopped Germany in the East.",
            "Midway (1942): USA beat Japan in the Pacific.",
            "El Alamein (1942): Britain beat Axis in N. Africa.",
            "After these, the Allies advanced.",
          ],
        },
        {
          type: "interactive",
          variant: "reveal",
          data: [
            { key: "question", value: "Which 1942–43 battle turned the Eastern Front against Germany?" },
            { key: "option_0", value: "Stalingrad" },
            { key: "option_1", value: "Midway" },
            { key: "option_2", value: "D-Day" },
            { key: "option_3", value: "El Alamein" },
            { key: "answer", value: "Stalingrad" },
            { key: "explanation", value: "A whole German army was destroyed." },
          ],
        },
      ],
      questions: [
        { q: "Midway was a key battle in which theatre?", options: ["The Pacific", "Europe", "Africa", "Atlantic"], answer: "The Pacific", explain: "USA vs Japan." },
        { q: "El Alamein was fought in…", options: ["North Africa", "France", "Japan", "Russia"], answer: "North Africa", explain: "Britain vs Axis." },
        { q: "Stalingrad was a defeat for…", options: ["Germany", "the USA", "Britain", "Japan"], answer: "Germany", explain: "6th Army lost." },
        { q: "These battles all happened around…", options: ["1942–43", "1939–40", "1945", "1916"], answer: "1942–43", explain: "The turning point." },
        { q: "After these battles, the Allies…", options: ["went on the offensive", "surrendered", "signed peace", "did nothing"], answer: "went on the offensive", explain: "Tide had turned." },
      ],
    },
    {
      topic: "World War II",
      title: "D-Day & Victory in Europe",
      difficulty: "intermediate",
      minutes: 14,
      points: 90,
      summary: "On 6 June 1944 (D-Day), the Allies invaded Nazi-occupied France; Germany surrendered in May 1945.",
      blocks: [
        { type: "heading", text: "Return to France" },
        {
          type: "text",
          text: "On 6 June 1944 — D-Day — the Allies launched the largest seaborne invasion in history on the beaches of Normandy, France. Troops from Britain, the USA, Canada and many other nations stormed ashore under heavy fire. From this beachhead they liberated France and pushed toward Germany.\n\nAt the same time, the Soviet army closed in from the east. Germany was crushed between two vast armies. Hitler killed himself in April 1945, and on 8 May 1945 Germany surrendered (V-E Day). The war in Europe was over.",
        },
        {
          type: "example",
          text: "D-Day beaches had code names like Omaha (US) and Gold (British). Omaha saw terrible US casualties but the Allies held, opening the road to Berlin.",
        },
        {
          type: "keyPoints",
          items: [
            "D-Day: 6 June 1944, Normandy landings.",
            "Largest seaborne invasion in history.",
            "Germany squeezed from west and east.",
            "Germany surrendered 8 May 1945 (V-E Day).",
          ],
        },
        {
          type: "interactive",
          variant: "timeline",
          data: [
            { key: "1939", value: "Germany invades Poland; Britain & France declare war." },
            { key: "1941", value: "Germany invades USSR; USA enters war after Pearl Harbor." },
            { key: "1942-43", value: "Turning points: Stalingrad, Midway, El Alamein." },
            { key: "1944", value: "D-Day (6 June); Allies invade Normandy." },
            { key: "1945", value: "Germany surrenders (8 May, V-E Day)." },
          ],
        },
      ],
      questions: [
        { q: "D-Day was on…", options: ["6 June 1944", "6 June 1945", "11 Nov 1918", "1 Sept 1939"], answer: "6 June 1944", explain: "Normandy landings." },
        { q: "D-Day took place in…", options: ["Normandy, France", "Berlin, Germany", "Tokyo, Japan", "Rome, Italy"], answer: "Normandy, France", explain: "Northern coast." },
        { q: "Germany surrendered in Europe on…", options: ["8 May 1945 (V-E Day)", "8 May 1944", "11 Nov 1918", "2 Sept 1945"], answer: "8 May 1945 (V-E Day)", explain: "Victory in Europe." },
        { q: "Germany was squeezed by Allies from the west and…", options: ["the Soviets from the east", "Japan from the east", "Italy from the south only", "nowhere"], answer: "the Soviets from the east", explain: "Two-front collapse." },
        { q: "D-Day is best described as…", options: ["the largest seaborne invasion in history", "a naval treaty", "an air raid only", "a peace conference"], answer: "the largest seaborne invasion in history", explain: "Beach landings in Normandy." },
      ],
    },
    {
      topic: "World War II",
      title: "The End & Legacy",
      difficulty: "intermediate",
      minutes: 14,
      points: 90,
      summary: "Japan surrendered in August 1945 after atomic bombs; the UN was founded to prevent future world wars.",
      blocks: [
        { type: "heading", text: "The World After" },
        {
          type: "text",
          text: "After Germany's surrender, war continued against Japan. In August 1945, the USA dropped atomic bombs on Hiroshima and Nagasaki — terrible new weapons that killed over 100,000 people instantly. Japan surrendered on 2 September 1945. WWII was over; over 70 million people had died.\n\nThe war's legacy was huge. The United Nations was founded to keep peace. The horror of the Holocaust (the Nazi murder of 6 million Jews and others) shocked the world. The USA and Soviet Union emerged as rival superpowers, beginning the Cold War.",
        },
        {
          type: "example",
          text: "The United Nations, founded in 1945, replaced the failed League of Nations. Its goal: stop future wars through cooperation and international law.",
        },
        {
          type: "keyPoints",
          items: [
            "Atomic bombs on Hiroshima & Nagasaki (Aug 1945).",
            "Japan surrendered 2 Sept 1945.",
            "Over 70 million dead worldwide.",
            "UN founded to keep the peace.",
          ],
        },
        {
          type: "interactive",
          variant: "reveal",
          data: [
            { key: "question", value: "What major organisation was founded in 1945 to keep world peace?" },
            { key: "option_0", value: "The United Nations" },
            { key: "option_1", value: "NATO" },
            { key: "option_2", value: "The European Union" },
            { key: "option_3", value: "The League of Nations" },
            { key: "answer", value: "The United Nations" },
            { key: "explanation", value: "Replaced the failed League of Nations." },
          ],
        },
      ],
      questions: [
        { q: "Atomic bombs were dropped on which two cities?", options: ["Hiroshima & Nagasaki", "Tokyo & Osaka", "Berlin & Munich", "Beijing & Shanghai"], answer: "Hiroshima & Nagasaki", explain: "August 1945." },
        { q: "Japan surrendered on…", options: ["2 September 1945", "8 May 1945", "11 Nov 1918", "6 June 1944"], answer: "2 September 1945", explain: "End of WWII." },
        { q: "Approximate WWII death toll:", options: ["Over 70 million", "About 1 million", "About 100,000", "Few thousand"], answer: "Over 70 million", explain: "Deadliest conflict ever." },
        { q: "The Holocaust was the Nazi murder of…", options: ["6 million Jews and others", "no one", "100 people", "only soldiers"], answer: "6 million Jews and others", explain: "A horrific genocide." },
        { q: "After WWII, the USA and USSR became…", options: ["rival superpowers (Cold War)", "one country", "allies forever", "irrelevant"], answer: "rival superpowers (Cold War)", explain: "Beginning decades of tension." },
      ],
    },

    // ===================== AMERICAN FOUNDING & REVOLUTION (5) =====================
    {
      topic: "American Founding & Revolution",
      title: "The 13 Colonies",
      difficulty: "intermediate",
      minutes: 12,
      points: 80,
      summary: "By the 1700s, Britain had 13 colonies along North America's Atlantic coast, each with its own government but loyal to the King.",
      blocks: [
        { type: "heading", text: "Britain's American Colonies" },
        {
          type: "text",
          text: "Starting in the early 1600s, Britain founded colonies along the Atlantic coast of North America. By the 1700s there were 13 of them, from New Hampshire in the north to Georgia in the south. Each had its own assembly to make local laws, but all were loyal to the British King.\n\nThe colonies had different economies: the north had shipbuilding and trade; the middle colonies grew grain; the south relied on plantations (often using enslaved people). Over time, the colonists began to think of themselves as Americans.",
        },
        {
          type: "example",
          text: "The 13 colonies (1776): NH, MA, RI, CT, NY, NJ, PA, DE, MD, VA, NC, SC, GA — the future United States' original states.",
        },
        {
          type: "keyPoints",
          items: [
            "13 British colonies on the Atlantic coast.",
            "Each had its own assembly.",
            "All loyal to the British King.",
            "Different economies by region.",
          ],
        },
        {
          type: "interactive",
          variant: "reveal",
          data: [
            { key: "question", value: "How many British colonies were along the Atlantic coast?" },
            { key: "option_0", value: "13" },
            { key: "option_1", value: "50" },
            { key: "option_2", value: "5" },
            { key: "option_3", value: "100" },
            { key: "answer", value: "13" },
            { key: "explanation", value: "The original 13 colonies." },
          ],
        },
      ],
      questions: [
        { q: "How many original colonies were there?", options: ["13", "50", "10", "20"], answer: "13", explain: "Atlantic coast." },
        { q: "The colonies were loyal to…", options: ["the British King", "France", "Spain", "no one"], answer: "the British King", explain: "British colonies." },
        { q: "Which region relied on plantations?", options: ["The South", "New England", "Canada", "The West"], answer: "The South", explain: "Cash crops, enslaved labour." },
        { q: "Each colony had its own…", options: ["assembly (government)", "king", "navy only", "language"], answer: "assembly (government)", explain: "Local law-making." },
        { q: "Which is NOT one of the 13 colonies?", options: ["California", "Virginia", "New York", "Massachusetts"], answer: "California", explain: "Added much later." },
      ],
    },
    {
      topic: "American Founding & Revolution",
      title: "Taxes & Tension",
      difficulty: "intermediate",
      minutes: 12,
      points: 80,
      summary: "Britain taxed the colonies to pay for war but gave them no voice in Parliament — 'no taxation without representation'.",
      blocks: [
        { type: "heading", text: "No Taxation Without Representation" },
        {
          type: "text",
          text: "After a costly war with France, Britain needed money and taxed the colonies: the Stamp Act, the Tea Act and more. The colonists were angry not just because of the cost, but because they had no representatives in the British Parliament making these laws.\n\nThe cry 'no taxation without representation' captured their anger. Protests grew: the Boston Massacre (1770) and the Boston Tea Party (1773), when colonists dumped British tea in the harbour, pushed both sides toward war.",
        },
        {
          type: "example",
          text: "Boston Tea Party (1773): colonists disguised as Native Americans boarded British ships and tipped 342 chests of tea into the harbour to protest the Tea Act.",
        },
        {
          type: "keyPoints",
          items: [
            "Britain taxed colonies to pay its debts.",
            "Colonists had no MPs in Parliament.",
            "'No taxation without representation.'",
            "Boston Tea Party (1773) protested the Tea Act.",
          ],
        },
        {
          type: "interactive",
          variant: "reveal",
          data: [
            { key: "question", value: "What did 'no taxation without representation' mean?" },
            { key: "option_0", value: "Colonists wanted a say in laws that taxed them" },
            { key: "option_1", value: "Colonists wanted to pay more tax" },
            { key: "option_2", value: "Colonists wanted no laws at all" },
            { key: "option_3", value: "Colonists wanted Britain to rule more" },
            { key: "answer", value: "Colonists wanted a say in laws that taxed them" },
            { key: "explanation", value: "No MPs = unfair taxes." },
          ],
        },
      ],
      questions: [
        { q: "Why did Britain tax the colonies?", options: ["To pay debts after war with France", "For fun", "To build a palace", "To give gifts"], answer: "To pay debts after war with France", explain: "Costly war debts." },
        { q: "The Boston Tea Party protested the…", options: ["Tea Act", "Stamp Act", "Sugar Act", "Corn Laws"], answer: "Tea Act", explain: "Tea dumped in harbour." },
        { q: "'No taxation without representation' meant colonists wanted…", options: ["a say in tax laws", "to pay no tax ever", "more taxes", "a new king"], answer: "a say in tax laws", explain: "Elected representatives." },
        { q: "The Boston Massacre happened in…", options: ["1770", "1812", "1861", "1492"], answer: "1770", explain: "Tensions boiled over." },
        { q: "The colonists had how many MPs in Parliament?", options: ["Zero", "13", "100", "All of them"], answer: "Zero", explain: "No representation." },
      ],
    },
    {
      topic: "American Founding & Revolution",
      title: "The Declaration of Independence",
      difficulty: "intermediate",
      minutes: 12,
      points: 90,
      summary: "On 4 July 1776, the colonies declared independence, stating that all people are created equal with rights to life, liberty and the pursuit of happiness.",
      blocks: [
        { type: "heading", text: "A New Nation Born" },
        {
          type: "text",
          text: "As war broke out, the colonies decided to break away for good. On 4 July 1776, the Continental Congress adopted the Declaration of Independence, written mainly by Thomas Jefferson. It stated that all people are created equal, with unalienable rights to life, liberty and the pursuit of happiness.\n\nThis was a radical idea: that governments exist to protect people's rights, and when they don't, the people may form a new government. The 13 colonies became the United States of America.",
        },
        {
          type: "example",
          text: "Famous line: 'We hold these truths to be self-evident, that all men are created equal…' — though at the time, enslaved people, women and Native Americans were not yet treated equally.",
        },
        {
          type: "keyPoints",
          items: [
            "4 July 1776: Declaration of Independence.",
            "Mainly written by Thomas Jefferson.",
            "'All men are created equal.'",
            "Rights: life, liberty, pursuit of happiness.",
          ],
        },
        {
          type: "interactive",
          variant: "reveal",
          data: [
            { key: "question", value: "Who was the main author of the Declaration of Independence?" },
            { key: "option_0", value: "Thomas Jefferson" },
            { key: "option_1", value: "George Washington" },
            { key: "option_2", value: "Abraham Lincoln" },
            { key: "option_3", value: "Benjamin Franklin" },
            { key: "answer", value: "Thomas Jefferson" },
            { key: "explanation", value: "He wrote the core text." },
          ],
        },
      ],
      questions: [
        { q: "When was the Declaration adopted?", options: ["4 July 1776", "4 July 1876", "25 Dec 1776", "1 Jan 1776"], answer: "4 July 1776", explain: "Independence Day." },
        { q: "Who mainly wrote the Declaration?", options: ["Thomas Jefferson", "George Washington", "King George III", "John Adams"], answer: "Thomas Jefferson", explain: "Principal author." },
        { q: "The Declaration lists rights to life, liberty and…", options: ["the pursuit of happiness", "free tea", "no taxes", "a king"], answer: "the pursuit of happiness", explain: "Famous trio." },
        { q: "'All men are created ___'", options: ["equal", "different", "royal", "taxed"], answer: "equal", explain: "Core principle." },
        { q: "The Declaration argued governments exist to…", options: ["protect people's rights", "tax heavily", "fight forever", "be kings"], answer: "protect people's rights", explain: "Or be replaced." },
      ],
    },
    {
      topic: "American Founding & Revolution",
      title: "The Revolutionary War",
      difficulty: "intermediate",
      minutes: 14,
      points: 90,
      summary: "From 1775–1783 the colonies fought Britain for independence, winning crucial French help and final victory at Yorktown.",
      blocks: [
        { type: "heading", text: "War for Independence" },
        {
          type: "text",
          text: "The Revolutionary War (1775–1783) was fought between the colonies and mighty Britain. George Washington commanded the Continental Army through harsh winters (like Valley Forge), keeping the army alive despite little money and supplies.\n\nHelp from France (and later Spain and the Netherlands) was decisive: French troops and naval power helped trap the British at Yorktown in 1781. Britain surrendered there, and in 1783 the Treaty of Paris recognised the United States as an independent nation.",
        },
        {
          type: "example",
          text: "Battle of Yorktown (1781): Washington, with French troops on land and the French fleet blocking the sea, trapped British General Cornwallis. The British surrender ended major fighting.",
        },
        {
          type: "keyPoints",
          items: [
            "Revolutionary War: 1775–1783.",
            "Commander: George Washington.",
            "French help was decisive.",
            "Yorktown 1781 → British surrender.",
          ],
        },
        {
          type: "interactive",
          variant: "timeline",
          data: [
            { key: "1770", value: "Boston Massacre." },
            { key: "1773", value: "Boston Tea Party." },
            { key: "1775", value: "Revolutionary War begins." },
            { key: "1776", value: "Declaration of Independence." },
            { key: "1781", value: "British surrender at Yorktown." },
            { key: "1783", value: "Treaty of Paris — USA independent." },
          ],
        },
      ],
      questions: [
        { q: "Who commanded the Continental Army?", options: ["George Washington", "Thomas Jefferson", "King George III", "Napoleon"], answer: "George Washington", explain: "Later first President." },
        { q: "Which foreign ally's help was decisive?", options: ["France", "Spain only", "Mexico", "China"], answer: "France", explain: "Troops and navy." },
        { q: "Final major British surrender was at…", options: ["Yorktown (1781)", "Boston (1770)", "Saratoga (1777)", "New York (1776)"], answer: "Yorktown (1781)", explain: "End of major fighting." },
        { q: "The USA was recognised as independent by treaty in…", options: ["1783 (Treaty of Paris)", "1776", "1812", "1865"], answer: "1783 (Treaty of Paris)", explain: "Britain accepted independence." },
        { q: "Valley Forge is remembered as…", options: ["a harsh winter encampment", "a great battle victory", "a peace treaty", "a royal palace"], answer: "a harsh winter encampment", explain: "Washington's army endured it." },
      ],
    },
    {
      topic: "American Founding & Revolution",
      title: "The Constitution & New Nation",
      difficulty: "intermediate",
      minutes: 14,
      points: 90,
      summary: "In 1787 the Constitution set up a government of three branches with checks and balances; it remains the USA's supreme law.",
      blocks: [
        { type: "heading", text: "Building a Government" },
        {
          type: "text",
          text: "Independence won, the new nation needed a government. The first plan (Articles of Confederation) was too weak, so in 1787 leaders wrote the Constitution. It created three branches: the Legislative (Congress makes laws), the Executive (the President enforces laws) and the Judicial (courts interpret laws).\n\nA system of 'checks and balances' stops any one branch from becoming too powerful. The Constitution, with its first ten amendments (the Bill of Rights), remains the supreme law of the United States.",
        },
        {
          type: "example",
          text: "Checks and balances example: Congress passes a law, the President can veto it, but Congress can override a veto with enough votes; the Supreme Court can strike down laws that break the Constitution.",
        },
        {
          type: "keyPoints",
          items: [
            "Constitution written in 1787.",
            "Three branches: Legislative, Executive, Judicial.",
            "Checks and balances limit power.",
            "Bill of Rights = first 10 amendments.",
          ],
        },
        {
          type: "interactive",
          variant: "reveal",
          data: [
            { key: "question", value: "Which branch makes the laws?" },
            { key: "option_0", value: "Legislative (Congress)" },
            { key: "option_1", value: "Executive (President)" },
            { key: "option_2", value: "Judicial (Courts)" },
            { key: "option_3", value: "The military" },
            { key: "answer", value: "Legislative (Congress)" },
            { key: "explanation", value: "Congress writes and passes laws." },
          ],
        },
      ],
      questions: [
        { q: "How many branches of US government?", options: ["Three", "One", "Ten", "Fifty"], answer: "Three", explain: "Legislative, Executive, Judicial." },
        { q: "Which branch enforces laws?", options: ["Executive (President)", "Legislative", "Judicial", "Congress"], answer: "Executive (President)", explain: "President enforces." },
        { q: "The Constitution was written in…", options: ["1787", "1776", "1812", "1865"], answer: "1787", explain: "At the Philadelphia Convention." },
        { q: "Checks and balances exist to…", options: ["stop any branch being too powerful", "speed up laws", "remove the President", "tax the people"], answer: "stop any branch being too powerful", explain: "Each branch limits the others." },
        { q: "The first ten amendments are the…", options: ["Bill of Rights", "Declaration", "Preamble", "Constitution's end"], answer: "Bill of Rights", explain: "Protects individual rights." },
      ],
    },

    // ===================== WAR OF 1812 (4) =====================
    {
      topic: "War of 1812",
      title: "Causes of the War",
      difficulty: "advanced",
      minutes: 12,
      points: 90,
      summary: "Causes of the War of 1812 included British trade restrictions, impressment of US sailors, and support for Native American raids.",
      blocks: [
        { type: "heading", text: "Why America Declared War" },
        {
          type: "text",
          text: "The young United States was caught between Britain and France, who were at war. Britain blocked US trade with France and, worst of all, stopped American ships and forced ('impressed') US sailors into the British navy — sometimes thousands at a time.\n\nAmericans also blamed Britain for arming Native Americans who fought westward settlers. These insults built up until 'War Hawks' in Congress pushed for war. In June 1812 the US declared war on Britain — while Britain was already busy fighting Napoleon.",
        },
        {
          type: "example",
          text: "Impressment: British warships would halt a US merchant ship, claim some sailors were 'British deserters', and drag them into the Royal Navy — often against their will and against US sovereignty.",
        },
        {
          type: "keyPoints",
          items: [
            "British trade restrictions hurt US shipping.",
            "Impressment: forcing US sailors into the Royal Navy.",
            "Britain accused of arming Native Americans.",
            "US declared war in June 1812.",
          ],
        },
        {
          type: "interactive",
          variant: "reveal",
          data: [
            { key: "question", value: "What was 'impressment'?" },
            { key: "option_0", value: "Forcing US sailors into the British navy" },
            { key: "option_1", value: "A trade treaty" },
            { key: "option_2", value: "A kind of ship" },
            { key: "option_3", value: "A peace medal" },
            { key: "answer", value: "Forcing US sailors into the British navy" },
            { key: "explanation", value: "A major cause of the war." },
          ],
        },
      ],
      questions: [
        { q: "When did the US declare war in the War of 1812?", options: ["June 1812", "June 1814", "June 1776", "June 1861"], answer: "June 1812", explain: "Hence the name." },
        { q: "Impressment means…", options: ["forcing sailors into the navy", "trading goods", "signing treaties", "building ships"], answer: "forcing sailors into the navy", explain: "Britain stopped US ships." },
        { q: "Who was Britain already fighting in 1812?", options: ["Napoleon's France", "China", "Mexico", "Spain only"], answer: "Napoleon's France", explain: "Britain was stretched." },
        { q: "A key US complaint was British…", options: ["trade restrictions + impressment", "gifts of land", "low taxes", "free trade"], answer: "trade restrictions + impressment", explain: "Insults to US sovereignty." },
        { q: "'War Hawks' were…", options: ["members of Congress pushing for war", "a type of bird", "British generals", "Native leaders"], answer: "members of Congress pushing for war", explain: "They wanted to fight Britain." },
      ],
    },
    {
      topic: "War of 1812",
      title: "Burning of Washington & Fort McHenry",
      difficulty: "advanced",
      minutes: 14,
      points: 100,
      summary: "In 1814 British troops burned Washington, D.C., but Fort McHenry's defence inspired 'The Star-Spangled Banner'.",
      blocks: [
        { type: "heading", text: "The Capital Burns" },
        {
          type: "text",
          text: "In August 1814, British forces landed and defeated American defenders at Bladensburg, then marched into Washington, D.C. They burned the Capitol, the White House and other public buildings (First Lady Dolley Madison famously saved a portrait of Washington as she fled).\n\nWeeks later, the British bombarded Fort McHenry in Baltimore harbour through the night. But by dawn, the huge American flag still flew over the fort. Watching this, Francis Scott Key wrote a poem that became 'The Star-Spangled Banner' — the US national anthem.",
        },
        {
          type: "example",
          text: "Francis Key saw the flag at dawn on 14 September 1814 and wrote 'Defence of Fort M'Henry'. Set to a popular tune, it became the US anthem in 1931.",
        },
        {
          type: "keyPoints",
          items: [
            "1814: British burned Washington, D.C.",
            "Dolley Madison saved Washington's portrait.",
            "Fort McHenry held against bombardment.",
            "Inspired 'The Star-Spangled Banner'.",
          ],
        },
        {
          type: "interactive",
          variant: "timeline",
          data: [
            { key: "1812", value: "US declares war on Britain." },
            { key: "1813", value: "Naval battles on Great Lakes." },
            { key: "Aug 1814", value: "British burn Washington, D.C." },
            { key: "Sep 1814", value: "Fort McHenry holds → 'Star-Spangled Banner'." },
            { key: "1815", value: "Treaty of Ghent; Battle of New Orleans." },
          ],
        },
      ],
      questions: [
        { q: "What happened to Washington, D.C. in 1814?", options: ["British burned public buildings", "It was rebuilt fully", "Nothing", "It became independent"], answer: "British burned public buildings", explain: "Including the White House." },
        { q: "Which fort's defence inspired the US anthem?", options: ["Fort McHenry", "Fort Knox", "Fort Sumter", "Fortune"], answer: "Fort McHenry", explain: "At Baltimore harbour." },
        { q: "Who wrote the poem that became the anthem?", options: ["Francis Scott Key", "Thomas Jefferson", "George Washington", "Abraham Lincoln"], answer: "Francis Scott Key", explain: "Watching the bombardment." },
        { q: "Dolley Madison famously saved a…", options: ["portrait of George Washington", "crown", "treaty", "ship"], answer: "portrait of George Washington", explain: "As she fled the White House." },
        { q: "'The Star-Spangled Banner' became the official anthem in…", options: ["1931", "1814", "1776", "1865"], answer: "1931", explain: "Over a century later." },
      ],
    },
    {
      topic: "War of 1812",
      title: "The Star-Spangled Banner",
      difficulty: "advanced",
      minutes: 10,
      points: 80,
      summary: "Francis Scott Key's poem about Fort McHenry's flag became the US national anthem, 'The Star-Spangled Banner'.",
      blocks: [
        { type: "heading", text: "A Song Born in Battle" },
        {
          type: "text",
          text: "During the night of 13–14 September 1814, Francis Scott Key was held on a British ship watching the bombardment of Fort McHenry. He did not know if the fort would hold. At dawn, the huge garrison flag (42 × 30 feet) was still flying — the fort had survived.\n\nOvercome, Key wrote a poem called 'Defence of Fort M'Henry'. It was soon set to a well-known tune and renamed 'The Star-Spangled Banner'. It became hugely popular and was officially adopted as the US national anthem in 1931.",
        },
        {
          type: "example",
          text: "The opening line asks: 'O say can you see, by the dawn's early light…' — exactly what Key wondered as he strained to see if the flag still flew.",
        },
        {
          type: "keyPoints",
          items: [
            "Key wrote it after watching Fort McHenry.",
            "The flag surviving at dawn inspired him.",
            "Set to a popular tune of the day.",
            "Officially the anthem from 1931.",
          ],
        },
        {
          type: "interactive",
          variant: "reveal",
          data: [
            { key: "question", value: "What did Key see at dawn that inspired the poem?" },
            { key: "option_0", value: "The flag still flying over Fort McHenry" },
            { key: "option_1", value: "The fort in ruins" },
            { key: "option_2", value: "A British surrender on land" },
            { key: "option_3", value: "A burning ship" },
            { key: "answer", value: "The flag still flying over Fort McHenry" },
            { key: "explanation", value: "It meant the fort had held." },
          ],
        },
      ],
      questions: [
        { q: "Who wrote 'The Star-Spangled Banner'?", options: ["Francis Scott Key", "John Adams", "George Washington", "Betsy Ross"], answer: "Francis Scott Key", explain: "In 1814." },
        { q: "When did it become the official US anthem?", options: ["1931", "1814", "1776", "1900"], answer: "1931", explain: "Congress made it official." },
        { q: "Key watched the bombardment of…", options: ["Fort McHenry", "Fort Knox", "the White House", "New Orleans"], answer: "Fort McHenry", explain: "Baltimore harbour." },
        { q: "The poem begins 'O say can you see, by the ___'", options: ["dawn's early light", "night's dark sky", "noon's bright sun", "evening's glow"], answer: "dawn's early light", explain: "Famous opening." },
        { q: "The flag that inspired the song was…", options: ["huge (42 × 30 ft)", "tiny", "white only", "British"], answer: "huge (42 × 30 ft)", explain: "A garrison flag." },
      ],
    },
    {
      topic: "War of 1812",
      title: "The Treaty of Ghent & Effects",
      difficulty: "advanced",
      minutes: 12,
      points: 90,
      summary: "The 1814 Treaty of Ghent ended the war with few changes, but the USA gained confidence and a surge of national pride.",
      blocks: [
        { type: "heading", text: "An Uneventful Peace, a Lasting Feeling" },
        {
          type: "text",
          text: "The war's treaty, signed in Ghent (Belgium) on 24 December 1814, basically returned things to how they were before: no land changed hands, nothing was resolved about impressment (which had quietly stopped anyway). News traveled slowly, so the biggest US victory — at New Orleans in January 1815 — happened after the treaty was signed.\n\nYet the war's effects were huge. The USA proved it could stand up to Britain. A wave of national pride ('Era of Good Feelings') followed, and Native American resistance in the old Northwest was broken, opening more land to settlers.",
        },
        {
          type: "example",
          text: "Battle of New Orleans (8 January 1815): Andrew Jackson's crushing victory over the British — fought two weeks after the peace treaty was signed, because neither side yet knew.",
        },
        {
          type: "keyPoints",
          items: [
            "Treaty of Ghent: 24 December 1814.",
            "Returned borders to pre-war (status quo).",
            "Battle of New Orleans fought after the treaty.",
            "Boosted US national pride.",
          ],
        },
        {
          type: "interactive",
          variant: "reveal",
          data: [
            { key: "question", value: "What did the Treaty of Ghent change about borders?" },
            { key: "option_0", value: "Nothing — returned to pre-war lines" },
            { key: "option_1", value: "Gave Canada to the USA" },
            { key: "option_2", value: "Gave Florida to Britain" },
            { key: "option_3", value: "Split the USA in two" },
            { key: "answer", value: "Nothing — returned to pre-war lines" },
            { key: "explanation", value: "Status quo ante bellum." },
          ],
        },
      ],
      questions: [
        { q: "Where was the peace treaty signed?", options: ["Ghent, Belgium", "Paris, France", "Washington, D.C.", "London"], answer: "Ghent, Belgium", explain: "Treaty of Ghent." },
        { q: "When was the Treaty of Ghent signed?", options: ["24 December 1814", "4 July 1776", "8 May 1945", "1 Jan 1812"], answer: "24 December 1814", explain: "Christmas Eve." },
        { q: "The Battle of New Orleans was fought…", options: ["after the treaty was signed", "before the war started", "during the Revolution", "in 1865"], answer: "after the treaty was signed", explain: "Slow news." },
        { q: "Who won the Battle of New Orleans?", options: ["Andrew Jackson (USA)", "Britain", "France", "Spain"], answer: "Andrew Jackson (USA)", explain: "Crushing US victory." },
        { q: "A major effect of the war was…", options: ["a surge of US national pride", "US losing independence", "Britain taking back the colonies", "nothing at all"], answer: "a surge of US national pride", explain: "'Era of Good Feelings.'" },
      ],
    },

    // ===================== AMERICAN CIVIL WAR (5) =====================
    {
      topic: "American Civil War",
      title: "A Nation Divides (Causes)",
      difficulty: "advanced",
      minutes: 14,
      points: 100,
      summary: "The Civil War grew from slavery, states' rights and economic differences between the industrial North and plantation South.",
      blocks: [
        { type: "heading", text: "Two Americas" },
        {
          type: "text",
          text: "By the mid-1800s the United States was splitting apart. The North was more industrial, with small farms and a growing anti-slavery movement. The South's economy relied on large plantations (especially cotton) worked by enslaved people.\n\nThe central issue was slavery — whether it should spread into new western territories. Southern states also argued for 'states' rights' — that each state could overrule federal laws it disliked. When Abraham Lincoln, who opposed slavery's spread, won the 1860 election, southern states began to secede (leave the Union).",
        },
        {
          type: "example",
          text: "1860 election: Lincoln won with almost no southern votes. Within months, South Carolina and then ten more southern states seceded, forming the Confederate States of America.",
        },
        {
          type: "keyPoints",
          items: [
            "North = industrial, increasingly anti-slavery.",
            "South = plantation economy reliant on slavery.",
            "Key issue: slavery's spread to new territories.",
            "11 southern states seceded after Lincoln's 1860 win.",
          ],
        },
        {
          type: "interactive",
          variant: "reveal",
          data: [
            { key: "question", value: "Which was a CENTRAL cause of the Civil War?" },
            { key: "option_0", value: "Slavery" },
            { key: "option_1", value: "Tea taxes" },
            { key: "option_2", value: "Land in Europe" },
            { key: "option_3", value: "Fishing rights" },
            { key: "answer", value: "Slavery" },
            { key: "explanation", value: "Especially its spread to new territories." },
          ],
        },
      ],
      questions: [
        { q: "Which election triggered southern secession?", options: ["Lincoln's 1860 win", "Washington's 1789 win", "Jefferson's 1800 win", "Jackson's 1828 win"], answer: "Lincoln's 1860 win", explain: "South feared slavery's end." },
        { q: "The South's economy relied heavily on…", options: ["plantations + enslaved labour", "factories", "fishing", "gold mining"], answer: "plantations + enslaved labour", explain: "Especially cotton." },
        { q: "The seceding states formed the…", options: ["Confederate States of America", "Union of States", "United Nations", "Republic of America"], answer: "Confederate States of America", explain: "The Confederacy." },
        { q: "How many southern states seceded?", options: ["11", "13", "3", "50"], answer: "11", explain: "Formed the Confederacy." },
        { q: "'States' rights' was argued by the…", options: ["South", "North", "West only", "Europe"], answer: "South", explain: "To resist federal laws." },
      ],
    },
    {
      topic: "American Civil War",
      title: "Slavery & the Emancipation Proclamation",
      difficulty: "advanced",
      minutes: 14,
      points: 100,
      summary: "On 1 January 1863, Lincoln's Emancipation Proclamation declared enslaved people in Confederate states to be free.",
      blocks: [
        { type: "heading", text: "Freedom Declared" },
        {
          type: "text",
          text: "Early in the war, Lincoln's main aim was to save the Union. But in September 1862, after the Battle of Antietam, he issued a warning: if the Confederacy did not return, he would free its enslaved people. They did not return.\n\nOn 1 January 1863, the Emancipation Proclamation declared enslaved people in Confederate states to be free. It did not free everyone at once (border states were exempt), but it changed the war's purpose into a fight against slavery and opened the door for Black men to join the Union army.",
        },
        {
          type: "example",
          text: "After the Proclamation, nearly 200,000 Black soldiers and sailors served in the Union forces — a crucial boost that helped the North win.",
        },
        {
          type: "keyPoints",
          items: [
            "Emancipation Proclamation: 1 January 1863.",
            "Freed enslaved people in Confederate states.",
            "Changed the war into a fight against slavery.",
            "Let Black men join the Union army.",
          ],
        },
        {
          type: "interactive",
          variant: "reveal",
          data: [
            { key: "question", value: "What did the Emancipation Proclamation do?" },
            { key: "option_0", value: "Declared enslaved people in Confederate states free" },
            { key: "option_1", value: "Ended the war" },
            { key: "option_2", value: "Started the war" },
            { key: "option_3", value: "Freed the British" },
            { key: "answer", value: "Declared enslaved people in Confederate states free" },
            { key: "explanation", value: "From 1 January 1863." },
          ],
        },
      ],
      questions: [
        { q: "When was the Emancipation Proclamation issued?", options: ["1 January 1863", "4 July 1776", "11 Nov 1918", "1 Jan 1865"], answer: "1 January 1863", explain: "During the Civil War." },
        { q: "Who issued it?", options: ["Abraham Lincoln", "Jefferson Davis", "George Washington", "Ulysses S. Grant"], answer: "Abraham Lincoln", explain: "US President." },
        { q: "The Proclamation freed enslaved people in…", options: ["Confederate states", "all states instantly", "Britain", "Canada"], answer: "Confederate states", explain: "Border states exempt." },
        { q: "After it, Black men could…", options: ["join the Union army", "vote everywhere", "own plantations", "leave the USA"], answer: "join the Union army", explain: "~200,000 served." },
        { q: "Slavery was finally abolished everywhere by the…", options: ["13th Amendment (1865)", "1st Amendment", "Emancipation Proclamation alone", "Treaty of Ghent"], answer: "13th Amendment (1865)", explain: "After Lincoln's death." },
      ],
    },
    {
      topic: "American Civil War",
      title: "Major Battles",
      difficulty: "advanced",
      minutes: 14,
      points: 100,
      summary: "Key battles — Fort Sumter, Antietam, Gettysburg and Vicksburg — shaped the Civil War's course.",
      blocks: [
        { type: "heading", text: "The War's Biggest Clashes" },
        {
          type: "text",
          text: "The war began on 12 April 1861 when Confederates fired on Fort Sumter, South Carolina. The bloodiest single day in American military history was Antietam (17 September 1862), which gave Lincoln the chance to issue the Emancipation Proclamation.\n\nThe turning point was Gettysburg (July 1863), a huge Union victory in Pennsylvania that ended Confederate hopes of invading the North. At the same time, the Union captured Vicksburg, gaining control of the Mississippi River and splitting the Confederacy in two.",
        },
        {
          type: "example",
          text: "Gettysburg (1–3 July 1863): over three days, ~51,000 casualties. On the final day, 'Pickett's Charge' — a disastrous Confederate infantry assault — was repelled. The South never invaded North again.",
        },
        {
          type: "keyPoints",
          items: [
            "Fort Sumter (1861): war begins.",
            "Antietam (1862): bloodiest single day.",
            "Gettysburg (1863): turning point.",
            "Vicksburg (1863): Union controls the Mississippi.",
          ],
        },
        {
          type: "interactive",
          variant: "timeline",
          data: [
            { key: "1861", value: "Fort Sumter — war begins." },
            { key: "1862", value: "Antietam — bloodiest single day; Proclamation planned." },
            { key: "1863", value: "Gettysburg & Vicksburg — turning points." },
            { key: "1865", value: "Lee surrenders at Appomattox." },
          ],
        },
      ],
      questions: [
        { q: "Where did the Civil War begin?", options: ["Fort Sumter", "Gettysburg", "Vicksburg", "Antietam"], answer: "Fort Sumter", explain: "April 1861." },
        { q: "Which was the war's turning point in the East?", options: ["Gettysburg (1863)", "Fort Sumter", "Yorktown", "New Orleans"], answer: "Gettysburg (1863)", explain: "Huge Union win." },
        { q: "Antietam is known as…", options: ["the bloodiest single day in US military history", "a naval battle", "a peace treaty", "a parade"], answer: "the bloodiest single day in US military history", explain: "17 Sept 1862." },
        { q: "Capturing Vicksburg gave the Union control of the…", options: ["Mississippi River", "Atlantic Ocean", "Great Lakes", "Rio Grande"], answer: "Mississippi River", explain: "It split the Confederacy." },
        { q: "When was Gettysburg fought?", options: ["July 1863", "April 1861", "September 1862", "April 1865"], answer: "July 1863", explain: "Three-day battle." },
      ],
    },
    {
      topic: "American Civil War",
      title: "Lincoln & Leadership",
      difficulty: "advanced",
      minutes: 12,
      points: 90,
      summary: "Abraham Lincoln led the Union through the war, holding it together and redefining its purpose at Gettysburg.",
      blocks: [
        { type: "heading", text: "A Steady Hand" },
        {
          type: "text",
          text: "Abraham Lincoln was President of the United States throughout the Civil War (1861–1865). He kept the border states in the Union, endured terrible personal loss and political attacks, and slowly found the generals (especially Ulysses S. Grant) who could win.\n\nLincoln redefined the war as a moral struggle against slavery. At Gettysburg in November 1863, in just 272 words, he honoured the dead and called for 'a new birth of freedom' — government 'of the people, by the people, for the people'. On 14 April 1865, just days after the war ended, he was assassinated.",
        },
        {
          type: "example",
          text: "Gettysburg Address: 'Four score and seven years ago…' — one of the most famous speeches in history, delivered in under three minutes.",
        },
        {
          type: "keyPoints",
          items: [
            "Lincoln: President 1861–1865.",
            "Held the Union together.",
            "Gettysburg Address: 'government of the people…'",
            "Assassinated 14 April 1865.",
          ],
        },
        {
          type: "interactive",
          variant: "reveal",
          data: [
            { key: "question", value: "What famous phrase did Lincoln use at Gettysburg?" },
            { key: "option_0", value: "'Government of the people, by the people, for the people'" },
            { key: "option_1", value: "'No taxation without representation'" },
            { key: "option_2", value: "'I have a dream'" },
            { key: "option_3", value: "'Ask not what your country can do for you'" },
            { key: "answer", value: "'Government of the people, by the people, for the people'" },
            { key: "explanation", value: "From the Gettysburg Address." },
          ],
        },
      ],
      questions: [
        { q: "Who was US President during the Civil War?", options: ["Abraham Lincoln", "Jefferson Davis", "Ulysses S. Grant", "Andrew Johnson"], answer: "Abraham Lincoln", explain: "1861–1865." },
        { q: "What did Lincoln do at Gettysburg?", options: ["Gave a famous short address", "Signed a treaty", "Fought a duel", "Surrendered"], answer: "Gave a famous short address", explain: "272 words." },
        { q: "When was Lincoln assassinated?", options: ["14 April 1865", "4 July 1776", "22 Nov 1963", "1 Jan 1863"], answer: "14 April 1865", explain: "Days after war ended." },
        { q: "Lincoln's top general was…", options: ["Ulysses S. Grant", "Robert E. Lee", "George Washington", "Stonewall Jackson"], answer: "Ulysses S. Grant", explain: "Later also President." },
        { q: "Lincoln redefined the war as a fight against…", options: ["slavery", "France", "taxes", "industry"], answer: "slavery", explain: "After the Proclamation." },
      ],
    },
    {
      topic: "American Civil War",
      title: "Reconstruction & Aftermath",
      difficulty: "advanced",
      minutes: 14,
      points: 100,
      summary: "After the war (1865), the Union rebuilt the South, abolished slavery and passed amendments — but deep divisions remained.",
      blocks: [
        { type: "heading", text: "Rebuilding a Broken Nation" },
        {
          type: "text",
          text: "The Civil War ended in April 1865 when Confederate General Robert E. Lee surrendered to Grant at Appomattox. Over 600,000 soldiers had died. The South's economy and society were shattered.\n\n'Reconstruction' (1865–1877) was the effort to rebuild and reunite. The 13th Amendment abolished slavery nationwide; the 14th gave citizenship to all born in the USA; the 15th said voting rights could not be denied by race. But promises of equality were soon undermined by segregation ('Jim Crow' laws) that lasted into the 1960s.",
        },
        {
          type: "example",
          text: "Appomattox Court House, 9 April 1865: Lee surrendered to Grant. Grant allowed Lee's men to keep their horses — a gesture of healing as the war ended.",
        },
        {
          type: "keyPoints",
          items: [
            "War ended April 1865 (Appomattox).",
            "Over 600,000 soldiers died.",
            "13th, 14th, 15th Amendments.",
            "Reconstruction 1865–1877; segregation followed.",
          ],
        },
        {
          type: "interactive",
          variant: "reveal",
          data: [
            { key: "question", value: "What did the 13th Amendment do?" },
            { key: "option_0", value: "Abolished slavery nationwide" },
            { key: "option_1", value: "Gave women the vote" },
            { key: "option_2", value: "Lowered taxes" },
            { key: "option_3", value: "Created the army" },
            { key: "answer", value: "Abolished slavery nationwide" },
            { key: "explanation", value: "Passed in 1865." },
          ],
        },
      ],
      questions: [
        { q: "Where did Lee surrender to Grant?", options: ["Appomattox (1865)", "Gettysburg", "Vicksburg", "Washington"], answer: "Appomattox (1865)", explain: "9 April 1865." },
        { q: "Roughly how many soldiers died in the Civil War?", options: ["Over 600,000", "About 10,000", "About 1,000", "Over 6 million"], answer: "Over 600,000", explain: "America's deadliest war." },
        { q: "The 13th Amendment…", options: ["abolished slavery", "gave women the vote", "freed the British", "made the President king"], answer: "abolished slavery", explain: "1865." },
        { q: "Reconstruction lasted from 1865 to…", options: ["1877", "1865 only", "1900", "1920"], answer: "1877", explain: "Then federal troops withdrew." },
        { q: "After Reconstruction, the South saw the rise of…", options: ["'Jim Crow' segregation laws", "equal rights for all", "no government", "a new king"], answer: "'Jim Crow' segregation laws", explain: "Lasted into the 1960s." },
      ],
    },
  ],
};
